Ready for review
nonhakobyan11/Java-Homeworks pull request #7
Opened 2020-01-31 11:55 UTC by nonhakobyan11

2020-02-03 15:33 UTC, apatian requested changes
Good job!

2020-02-03 15:33 UTC, apatian commented on Maps_Enum_HW/homework3/task2/Month.java
> +    public void setFebruaryDays() {
Consider renaming to setFebruaryDaysForLeapYear

2020-02-03 15:33 UTC, apatian commented on Maps_Enum_HW/homework3/task2/Service.java
> +        if (month == Month.FEBRUARY && year % 4 == 0) {
Checking for a leap year is not that straightforward https://www.timeanddate.com/date/leapyear.html , 
so you may want to use a library method https://www.baeldung.com/java-leap-year

2020-02-03 15:33 UTC, apatian commented on Maps_Enum_HW/homework3/task2/Service.java
> +            month.setFebruaryDays();
Strive not to change the state in a get method
https://martinfowler.com/bliki/CommandQuerySeparation.html

2020-02-04 12:12 UTC, aram-hakobyan commented on Maps_Enum_HW/homework3/task1/StudentService.java
> +public class StudentService {
Please create these maps inside the appropriate methods, otherwise you will get a mess when calling the methods multiple times.

2020-02-05 08:11 UTC, apatian approved these changes

2020-02-06 09:03 UTC, aram-hakobyan approved these changes

2020-02-06 11:00 UTC, merged